### PR TITLE
IOPS-000 update main examples files with fhir-converter

### PR DESCRIPTION
**Pull request by artronics**
These are the files currently on fhir-converter master. I said during that meeting that `changeSummary` is the only change but I forgot that we merged AllergyIntolerance `extensionId` as well.

### CODE REVIEW

**Comment by declankieran** [comment]
@artronics Is this everything you need from the develop branch? The last merge into main was 4 PR's before this one, main is currently 44 commits behind develop.

**Comment by artronics** [comment]
@declankieran-nhsd I'll open a pr from develop to main to see if changes are correct.

**Comment by artronics** [comment]
@declankieran-nhsd I opened a pr from `develop` to `master` just to check the diff. Most of the changes are not in `careconnect-to-ukcore`. In fhir-converter we only copy that directory because that's the only one we need for our testing.

**Comment by declankieran** [comment]
@artronics Would it suit to merge this into develop, and then creare a new PR with only the changes from the careconnect-to-ukcore folder.  However, this would essentially give you everything in terms of example/maps, as the other folders are just documentation or test scripts etc...   So not sure what it is you need to exclude, but at that point it seems like merging this into develop and then merging into main would be much the same thing...

If there is something that needs removed from develop, I think you'd be better cutting a branch off of develop and then adding/removing what you need, before creating a PR to merge into main, rather than cutting from main which seems to be the case in this one.

**Comment by JalfResi** [comment]
We're just reviewing the commit ourselves Declan - we want to have a single, simple PR that brings your main into alignment with the work we've done. Give us a few moments to double check things our end.

**Comment by JalfResi** [comment]
Just reviewed - turns out we only pulled from the develop branch once, at the beginning of our work, so we are infact in-sync with main(except for the files in this pull request, which are the examples for allergyintollerance that you and jalal had discussed previously). 

This PR will bring your main branch into sync with the FHIR-Converter we have developed. Can you please merge this, and tag the commit as v0.1.

**Comment by declankieran** [comment]
@JalfResi Looking at this, to fix the pipeline I would need to rename the ExtensionId example see https://github.com/NHSDigital/fhir-transforms/pull/47. I also need to make a map for the ChangeSummary, but as you are not carrying it over there would be much to it.  Also, as you're only concerned with the examples, I'm guessing the map shouldn't matter.   Are you ok if I update the branch to fix the pipeline before I merge it in?

**Comment by artronics** [comment]
@declankieran-nhsd Ben is off for two weeks. Yeah we only copy that example directory. About changes, initially we copied from the develop branch. That's why there are no many changes.

**Comment by declankieran** [comment]
@artronics Are you happy enough then if I fix this PR by renaming the AllergyIntoleranceExtensionId-Extension-3to4_000.json files and creating a map for MedicationStatementChangeSummary-Extension-3to4_000.json.  I'll then tag it as v0.1.0 and create a release.

**Comment by artronics** [comment]
@declankieran-nhsd Do you think we can merge this soon? I'm asking because we're trying to finalise the spec documentation and we should mentioned a version number. I go for `v0.1.0` as you suggested but it would be good to tag it so our docs are aligned.

**Comment by declankieran** [comment]
@artronics Sure, I'll make the fixes and create a release

**Comment by declankieran** [comment]
@artronics https://github.com/NHSDigital/fhir-transforms/releases/tag/v.0.1.0

**Pull request merged**
